DROP TABLE IF EXISTS CATALOGUE_ITEMS;
CREATE TABLE CATALOGUE_ITEMS (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    SKU_NUMBER VARCHAR(16) NOT NULL,
    ITEM_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL,
    CATEGORY VARCHAR(255) NOT NULL,
    PRICE DOUBLE NOT NULL,
    INVENTORY INT NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_ON TIMESTAMP
);
DROP TABLE IF EXISTS ALUMNOS;
CREATE TABLE ALUMNOS (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    apellidos VARCHAR(255) NOT NULL,
    estado INTEGER,
    edad INTEGER
);
DROP TABLE IF EXISTS TRACEMSG;
CREATE TABLE TRACEMSG (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    sessionId VARCHAR(255) NOT NULL,
    payload VARCHAR(255) NOT NULL,
    ts TIMESTAMP
);